version: "3.3"

services:
  departmentservice-db:
    image: mysql:latest
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: 'departmentservice_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
